---

calibre_name: calibre
calibre_image: linuxserver/calibre
calibre_ports:
  - 8080:8080
  - 8081:8081
calibre_config_directory: "{{ common_books_directory }}/calibre"
calibre_books_directory: "{{ common_books_directory }}"
calibre_environment_variables:
  PUID: "1000"
  PGID: "1000"
  TZ: Sydney/Australia
  #GUAC_USER: abc
  #GUAC_PASS: 900150983cd24fb0d6963f7d28e17f72

calibre_docker_additional_options:
  restart_policy: unless-stopped
